rest_api_url: "https://kiwi.ulakhaberlesme.com.tr/json-rpc/"
rest_api_username: "admin.test"
rest_api_password: "Test123456789"
jenkins_url: "https://jenkins-5gcn.ulakhaberlesme.com.tr"
jenkins_username: "cem.topkaya"
jenkins_token: "110b033bff6a4bed641ab76fa6f3704896"
deployment_job_path: "view/DevOps/job/DevOps/job/5GCN-Deployment"
deployment_job_token: "5gcn_deploy"
